# Generated by Django 5.2.13 on 2026-04-26 14:18

import django.db.models.deletion
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name.", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the wrapping element's class (theme-<slug>).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when a page has no theme set and no Site setting matches.",
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System (follow OS)"),
                        ],
                        default="system",
                        help_text="Initial theme mode when the visitor has no preference saved.",
                        max_length=10,
                    ),
                ),
                ("light_bg", models.CharField(default="#ffffff", max_length=64)),
                ("light_surface", models.CharField(default="#f8fafc", max_length=64)),
                (
                    "light_text_primary",
                    models.CharField(default="#0f172a", max_length=64),
                ),
                (
                    "light_text_secondary",
                    models.CharField(default="#475569", max_length=64),
                ),
                (
                    "light_text_muted",
                    models.CharField(default="#94a3b8", max_length=64),
                ),
                ("light_border", models.CharField(default="#e2e8f0", max_length=64)),
                ("dark_bg", models.CharField(default="#0f172a", max_length=64)),
                ("dark_surface", models.CharField(default="#1e293b", max_length=64)),
                (
                    "dark_text_primary",
                    models.CharField(default="#f8fafc", max_length=64),
                ),
                (
                    "dark_text_secondary",
                    models.CharField(default="#cbd5e1", max_length=64),
                ),
                ("dark_text_muted", models.CharField(default="#64748b", max_length=64)),
                ("dark_border", models.CharField(default="#334155", max_length=64)),
                ("success_color", models.CharField(default="#16a34a", max_length=64)),
                ("warning_color", models.CharField(default="#f59e0b", max_length=64)),
                ("error_color", models.CharField(default="#dc2626", max_length=64)),
                ("info_color", models.CharField(default="#2563eb", max_length=64)),
                ("link_color", models.CharField(default="#2563eb", max_length=64)),
                (
                    "focus_ring_color",
                    models.CharField(default="#3b82f6", max_length=64),
                ),
                ("success_color_dark", models.CharField(blank=True, max_length=64)),
                ("warning_color_dark", models.CharField(blank=True, max_length=64)),
                ("error_color_dark", models.CharField(blank=True, max_length=64)),
                ("info_color_dark", models.CharField(blank=True, max_length=64)),
                ("link_color_dark", models.CharField(blank=True, max_length=64)),
                ("focus_ring_color_dark", models.CharField(blank=True, max_length=64)),
                (
                    "heading_font",
                    models.CharField(
                        default="system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
                        help_text="CSS font-family stack for headings.",
                        max_length=255,
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        default="system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
                        help_text="CSS font-family stack for body text.",
                        max_length=255,
                    ),
                ),
                (
                    "custom_fonts_css_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to a stylesheet (e.g. Google Fonts) to load.",
                    ),
                ),
                (
                    "heading_font_weight",
                    models.CharField(
                        choices=[
                            ("300", "Light (300)"),
                            ("400", "Regular (400)"),
                            ("500", "Medium (500)"),
                            ("600", "Semibold (600)"),
                            ("700", "Bold (700)"),
                            ("800", "Extrabold (800)"),
                        ],
                        default="700",
                        max_length=8,
                    ),
                ),
                (
                    "body_font_weight",
                    models.CharField(
                        choices=[
                            ("300", "Light (300)"),
                            ("400", "Regular (400)"),
                            ("500", "Medium (500)"),
                            ("600", "Semibold (600)"),
                            ("700", "Bold (700)"),
                            ("800", "Extrabold (800)"),
                        ],
                        default="400",
                        max_length=8,
                    ),
                ),
                (
                    "font_scale",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("normal", "Normal"),
                            ("large", "Large"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("radius_sm", models.CharField(default="0.25rem", max_length=32)),
                ("radius_md", models.CharField(default="0.5rem", max_length=32)),
                ("radius_lg", models.CharField(default="1rem", max_length=32)),
                ("radius_full", models.CharField(default="9999px", max_length=32)),
                (
                    "shadow_sm",
                    models.CharField(
                        default="0 1px 2px 0 rgb(0 0 0 / 0.05)", max_length=255
                    ),
                ),
                (
                    "shadow_md",
                    models.CharField(
                        default="0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
                        max_length=255,
                    ),
                ),
                (
                    "shadow_lg",
                    models.CharField(
                        default="0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "ordering": ["name"],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BrandColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Primary', 'Secondary', 'Accent'",
                        max_length=100,
                    ),
                ),
                (
                    "color_value",
                    models.CharField(
                        help_text="Hex (#fff), rgb(), rgba(), or a CSS gradient.",
                        max_length=500,
                    ),
                ),
                (
                    "color_value_dark",
                    models.CharField(
                        blank=True,
                        help_text="Optional dark-mode override.",
                        max_length=500,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_colors",
                        to="wagtail_themes.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand color",
                "verbose_name_plural": "Brand colors",
                "ordering": ["sort_order", "name"],
                "unique_together": {("theme", "name")},
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
