# Generated by Django 5.2.13 on 2026-04-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_themes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("set_active_theme", "Can set the active theme on a page or site")
                ],
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
    ]
