# Generated by Django 5.2.13 on 2026-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_themes", "0002_alter_theme_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandcolor",
            name="color_value",
            field=models.CharField(
                help_text="Light-mode value. Accepts hex (#3b82f6, #fff), rgb()/rgba(), or any CSS gradient (linear-gradient, radial-gradient, …). Solids additionally emit a 50→950 shade scale and an -rgb companion for Tailwind opacity utilities.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="brandcolor",
            name="color_value_dark",
            field=models.CharField(
                blank=True,
                help_text="Dark-mode value. Optional — leave blank to reuse the light value. Useful when a colour that pops on white looks washed out on navy.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="brandcolor",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive colours are hidden from CSS output but kept in the admin for reference. Useful for retiring a colour without losing history.",
            ),
        ),
        migrations.AlterField(
            model_name="brandcolor",
            name="name",
            field=models.CharField(
                help_text="Short, CSS-friendly name — e.g. 'Primary', 'Secondary', 'Accent', 'Aurora'. The slug becomes part of the variable: a name 'Primary Brand' yields --color-primary-brand. Keep names consistent across themes so swapping themes doesn't break references in your CSS.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="brandcolor",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first in admin lists."
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark_bg",
            field=models.CharField(
                default="#0f172a",
                help_text="Page background in dark mode.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark_border",
            field=models.CharField(
                default="#334155",
                help_text="Border colour in dark mode.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark_surface",
            field=models.CharField(
                default="#1e293b",
                help_text="Card / panel background in dark mode.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark_text_muted",
            field=models.CharField(
                default="#64748b",
                help_text="Disabled / placeholder text in dark mode.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark_text_primary",
            field=models.CharField(
                default="#f8fafc",
                help_text="Body text colour in dark mode.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark_text_secondary",
            field=models.CharField(
                default="#cbd5e1", help_text="Subdued text in dark mode.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="error_color",
            field=models.CharField(
                default="#dc2626",
                help_text="Used for destructive actions, validation errors, error toasts.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="error_color_dark",
            field=models.CharField(
                blank=True, help_text="Optional dark-mode override.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="focus_ring_color",
            field=models.CharField(
                default="#3b82f6",
                help_text="Outline colour for keyboard focus. Should contrast strongly with both --color-bg and surrounding interactive elements.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="focus_ring_color_dark",
            field=models.CharField(
                blank=True, help_text="Optional dark-mode override.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="info_color",
            field=models.CharField(
                default="#2563eb",
                help_text="Used for informational banners and neutral notifications.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="info_color_dark",
            field=models.CharField(
                blank=True, help_text="Optional dark-mode override.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light_bg",
            field=models.CharField(
                default="#ffffff",
                help_text="Page background in light mode. Emits --color-bg.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light_border",
            field=models.CharField(
                default="#e2e8f0",
                help_text="Border colour for cards, dividers, inputs.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light_surface",
            field=models.CharField(
                default="#f8fafc",
                help_text="Card / panel background, slightly different from page background. Use for nested content. Emits --color-surface.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light_text_muted",
            field=models.CharField(
                default="#94a3b8",
                help_text="Disabled / placeholder text. Lower contrast intentional.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light_text_primary",
            field=models.CharField(
                default="#0f172a",
                help_text="Body text colour. Aim for ≥7:1 contrast against --color-bg.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light_text_secondary",
            field=models.CharField(
                default="#475569",
                help_text="Subdued text — captions, metadata. Should still pass AA contrast.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="link_color",
            field=models.CharField(
                default="#2563eb",
                help_text="Default anchor colour. Often the same as a brand colour.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="link_color_dark",
            field=models.CharField(
                blank=True, help_text="Optional dark-mode override.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="success_color",
            field=models.CharField(
                default="#16a34a",
                help_text="Used for confirmations, valid form state, success toasts.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="success_color_dark",
            field=models.CharField(
                blank=True,
                help_text="Optional dark-mode override. Leave blank to reuse the light value.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="warning_color",
            field=models.CharField(
                default="#f59e0b",
                help_text="Used for cautions, expiring states, banners.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="warning_color_dark",
            field=models.CharField(
                blank=True, help_text="Optional dark-mode override.", max_length=64
            ),
        ),
    ]
